/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "sidebar": "auto",
        "home": true,
        "heroImage": "/hero.png",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "粤ICP备19120525号 联系电话：18813216278"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-59a501ba",
      "path": "/"
    },
    {
      "title": "关于我的自我介绍",
      "frontmatter": {
        "title": "关于我的自我介绍"
      },
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-5c920b54",
      "path": "/about/",
      "headers": [
        {
          "level": 2,
          "title": "自我介绍",
          "slug": "自我介绍"
        },
        {
          "level": 2,
          "title": "自我介绍2",
          "slug": "自我介绍2"
        },
        {
          "level": 2,
          "title": "自我介绍3",
          "slug": "自我介绍3"
        },
        {
          "level": 2,
          "title": "自我介绍4",
          "slug": "自我介绍4"
        },
        {
          "level": 2,
          "title": "自我介绍5",
          "slug": "自我介绍5"
        }
      ]
    },
    {
      "title": "关于我",
      "frontmatter": {
        "title": "关于我",
        "sidebar": "auto"
      },
      "regularPath": "/about/a.html",
      "relativePath": "about/a.md",
      "key": "v-3beebdaa",
      "path": "/about/a.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        }
      ]
    },
    {
      "title": "这是我的第一篇md",
      "frontmatter": {},
      "regularPath": "/js.html",
      "relativePath": "js.md",
      "key": "v-c2c3fe9c",
      "path": "/js.html"
    }
  ],
  "themeConfig": {
    "displayAllHeaders": true,
    "sidebar": "auto",
    "nav": [
      {
        "text": "面试",
        "link": "/"
      },
      {
        "text": "算法",
        "link": "/guide/"
      },
      {
        "text": "学习笔记",
        "link": "https://google.com"
      },
      {
        "text": "关于",
        "link": "/about/"
      }
    ],
    "lastUpdated": "Last Updated"
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "title": "内容管理系统",
      "description": "Vue-powered Static Site Generator",
      "path": "/"
    },
    "/zh/": {
      "lang": "zh-CN",
      "title": "内容管理系统",
      "description": "Vue 驱动的静态网站生成器",
      "path": "/zh/"
    }
  }
}