/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "内容管理系统",
      "frontmatter": {
        "title": "内容管理系统",
        "sidebar": "auto",
        "home": true,
        "heroImage": "http://127.0.0.1:7001/public/uploads/avatar/2021/03/02/1614689963739764.jpg",
        "heroText": "内容管理系统",
        "tagline": "作者:casey",
        "actionText": "关于作者 →",
        "actionLink": "/about/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "粤ICP备19120525号 联系电话：18813216278"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-11851a37",
      "path": "/",
      "lastUpdated": "2021-3-10 17:27:47"
    },
    {
      "title": "关于我",
      "frontmatter": {
        "title": "关于我",
        "tags": [
          "JavaScript",
          "Vue"
        ],
        "author": "Billyyyyy3320",
        "location": "广东深圳"
      },
      "regularPath": "/about/a.html",
      "relativePath": "about/a.md",
      "key": "v-510eb2d2",
      "path": "/about/a.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        }
      ],
      "lastUpdated": "2021-2-23 17:01:11"
    },
    {
      "title": "关于我的自我介绍",
      "frontmatter": {
        "title": "关于我的自我介绍"
      },
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-70d4af30",
      "path": "/about/",
      "headers": [
        {
          "level": 2,
          "title": "自我介绍",
          "slug": "自我介绍"
        },
        {
          "level": 3,
          "title": "目前正在学习",
          "slug": "目前正在学习"
        },
        {
          "level": 2,
          "title": "自我介绍2",
          "slug": "自我介绍2"
        },
        {
          "level": 2,
          "title": "自我介绍3",
          "slug": "自我介绍3"
        },
        {
          "level": 2,
          "title": "自我介绍4",
          "slug": "自我介绍4"
        },
        {
          "level": 2,
          "title": "自我介绍5",
          "slug": "自我介绍5"
        }
      ],
      "lastUpdated": "2021-2-23 17:01:11"
    },
    {
      "title": "这是标题1",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "测",
        "7": "试",
        "8": "1"
      },
      "regularPath": "/algorithm/",
      "relativePath": "algorithm/README.md",
      "key": "v-759a49a4",
      "path": "/algorithm/",
      "lastUpdated": "2021-2-22 19:36:34"
    },
    {
      "title": "这是标题1",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "测",
        "7": "试",
        "8": "1"
      },
      "regularPath": "/interview/",
      "relativePath": "interview/README.md",
      "key": "v-1110f100",
      "path": "/interview/",
      "lastUpdated": "2021-2-22 19:36:34"
    },
    {
      "title": "这是标题1",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "测",
        "7": "试",
        "8": "1"
      },
      "regularPath": "/notes/",
      "relativePath": "notes/README.md",
      "key": "v-3dfe0700",
      "path": "/notes/",
      "lastUpdated": "2021-2-22 19:36:34"
    },
    {
      "title": "这是我的第一篇md",
      "frontmatter": {},
      "regularPath": "/js.html",
      "relativePath": "js.md",
      "key": "v-73659d1e",
      "path": "/js.html",
      "lastUpdated": "2021-2-20 19:29:57"
    },
    {
      "title": "关于我测试2",
      "frontmatter": {
        "title": "关于我测试2"
      },
      "regularPath": "/about/b.html",
      "relativePath": "about/b.md",
      "key": "v-29d75d37",
      "path": "/about/b.html",
      "lastUpdated": "2021-2-23 20:25:06"
    }
  ],
  "themeConfig": {
    "smoothScroll": true,
    "displayAllHeaders": true,
    "nav": [
      {
        "text": "面试",
        "link": "/interview/"
      },
      {
        "text": "算法",
        "link": "/algorithm/"
      },
      {
        "text": "学习笔记",
        "link": "/notes/"
      },
      {
        "text": "关于",
        "link": "/about/"
      }
    ],
    "markdown": {
      "lineNumbers": true
    },
    "lastUpdated": "最近一次更新于",
    "logo": "/image/1613990992(1).jpg"
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "内容管理系统",
      "description": "Vue 驱动的静态网站生成器",
      "path": "/"
    },
    "/zh/": {
      "lang": "zh-CN",
      "title": "内容管理系统",
      "description": "Vue 驱动的静态网站生成器",
      "path": "/zh/"
    }
  }
}